# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Greet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Greet(object):
    def setupUi(self, Greet):
        Greet.setObjectName("Greet")
        Greet.resize(421, 201)
        Greet.setStyleSheet("background-color: rgb(248, 237, 215);")
        self.centralwidget = QtWidgets.QWidget(Greet)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(120, 40, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Champagne & Limousines")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setStyleSheet("background-color: rgb(226, 131, 180);\n"
"")
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(120, 110, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Champagne & Limousines")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button2.setFont(font)
        self.button2.setStyleSheet("background-color: rgb(226, 131, 180);\n"
"")
        self.button2.setObjectName("button2")
        Greet.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Greet)
        self.statusbar.setObjectName("statusbar")
        Greet.setStatusBar(self.statusbar)

        self.retranslateUi(Greet)
        QtCore.QMetaObject.connectSlotsByName(Greet)

    def retranslateUi(self, Greet):
        _translate = QtCore.QCoreApplication.translate
        Greet.setWindowTitle(_translate("Greet", "Greeting!!!"))
        self.button1.setText(_translate("Greet", "Login"))
        self.button2.setText(_translate("Greet", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Greet = QtWidgets.QMainWindow()
    ui = Ui_Greet()
    ui.setupUi(Greet)
    Greet.show()
    sys.exit(app.exec_())
