# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(421, 542)
        Login.setStyleSheet("background-color: rgb(248, 237, 215);")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(150, -40, 211, 151))
        font = QtGui.QFont()
        font.setFamily("Gagalin")
        font.setPointSize(24)
        self.label1.setFont(font)
        self.label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(30, 160, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Champagne & Limousines")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(160, 170, 221, 31))
        self.username.setObjectName("username")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(30, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Champagne & Limousines")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(160, 250, 221, 31))
        self.password.setObjectName("password")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(120, 490, 211, 21))
        self.label4.setObjectName("label4")
        self.createaccbutton = QtWidgets.QPushButton(self.centralwidget)
        self.createaccbutton.setGeometry(QtCore.QRect(300, 480, 101, 31))
        self.createaccbutton.setStyleSheet("background-color: rgb(226, 131, 180);")
        self.createaccbutton.setObjectName("createaccbutton")
        self.loginbutton = QtWidgets.QPushButton(self.centralwidget)
        self.loginbutton.setGeometry(QtCore.QRect(290, 320, 93, 28))
        self.loginbutton.setStyleSheet("background-color: rgb(226, 131, 180);\n"
"")
        self.loginbutton.setObjectName("loginbutton")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login Setup"))
        self.label1.setText(_translate("Login", "Login"))
        self.label2.setText(_translate("Login", "Username"))
        self.label3.setText(_translate("Login", "Password"))
        self.label4.setText(_translate("Login", "If you dont have account, click"))
        self.createaccbutton.setText(_translate("Login", "Create Account"))
        self.loginbutton.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
